name: Escaperoomlog
options:
  bundleIdPrefix: com.shimondeitel.escapelog
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  groupSortPosition: top
settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: "W7Q885Q59C"
    CODE_SIGN_STYLE: Automatic
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    TARGETED_DEVICE_FAMILY: "1"
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"
targets:
  Escaperoomlog:
    type: application
    platform: iOS
    sources:
      - path: Escaperoomlog
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.escapelog
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_FILE: Escaperoomlog/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: "YES"
        GENERATE_INFOPLIST_FILE: "NO"
  EscaperoomlogTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: EscaperoomlogTests
      - path: Escaperoomlog.storekit
    dependencies:
      - target: Escaperoomlog
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.escapelog.tests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
  EscaperoomlogUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: EscaperoomlogUITests
    dependencies:
      - target: Escaperoomlog
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.escapelog.uitests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
schemes:
  Escaperoomlog:
    build:
      targets:
        Escaperoomlog: all
        EscaperoomlogTests: [test]
        EscaperoomlogUITests: [test]
    run:
      config: Debug
      storeKitConfiguration: Escaperoomlog.storekit
    test:
      config: Debug
      storeKitConfiguration: Escaperoomlog.storekit
      targets:
        - EscaperoomlogTests
        - EscaperoomlogUITests
    archive:
      config: Release
